import type {
  CatalogResponse,
  CreateStepRequest,
  CreateTaskItemRequest,
  CreateTaskRequest,
  CreateWorkflowRequest,
  DecomposeTaskRequest,
  DeleteStepRequest,
  FindDuplicateStepsRequest,
  FindDuplicateStepsResponse,
  MergeDuplicateStepsRequest,
  MergeDuplicateStepsResponse,
  DuplicateStepGroup,
  DeleteTaskItemRequest,
  DeleteTaskRequest,
  DeleteWorkflowRequest,
  ExecuteTaskItemRequest,
  ExecuteTaskItemResponse,
  GitCommitRequest,
  GitCommitResponse,
  GitDiffResponse,
  GitFileDiffRequest,
  GitFileDiffResponse,
  GitStagePathsRequest,
  GitStatusResponse,
  GitUnstagePathsRequest,
  FileChange,
  FileChangeKind,
  ImportDecompositionRequest,
  ImportWorkflowDraftRequest,
  ImportWorkflowDraftResponse,
  ImportWorkflowEditRequest,
  ImportWorkflowEditResponse,
  ListByWorkspaceRequest,
  RequestAiDecomposeRequest,
  RequestAiDecomposeResponse,
  RequestAiWorkflowEditRequest,
  RequestAiWorkflowEditResponse,
  RequestAiWorkflowGenRequest,
  RequestAiWorkflowGenResponse,
  SeedPresetRequest,
  SeedPresetResponse,
  Step,
  Task,
  TaskItem,
  UpdateStepRequest,
  UpdateTaskItemRequest,
  UpdateTaskRequest,
  UpdateWorkflowRequest,
  Workflow,
  WorkOSChangedEvent,
} from './types';

function api() {
  return window.electronAPI.workOS;
}

export const workOSApi = {
  listSteps: (req: ListByWorkspaceRequest) => api().listSteps(req),
  createStep: (req: CreateStepRequest) => api().createStep(req),
  updateStep: (req: UpdateStepRequest) => api().updateStep(req),
  deleteStep: (req: DeleteStepRequest) => api().deleteStep(req),
  findDuplicateSteps: (req: FindDuplicateStepsRequest) => api().findDuplicateSteps(req),
  mergeDuplicateSteps: (req: MergeDuplicateStepsRequest) => api().mergeDuplicateSteps(req),

  listWorkflows: (req: ListByWorkspaceRequest) => api().listWorkflows(req),
  createWorkflow: (req: CreateWorkflowRequest) => api().createWorkflow(req),
  updateWorkflow: (req: UpdateWorkflowRequest) => api().updateWorkflow(req),
  deleteWorkflow: (req: DeleteWorkflowRequest) => api().deleteWorkflow(req),

  listTasks: (req: ListByWorkspaceRequest) => api().listTasks(req),
  createTask: (req: CreateTaskRequest) => api().createTask(req),
  updateTask: (req: UpdateTaskRequest) => api().updateTask(req),
  deleteTask: (req: DeleteTaskRequest) => api().deleteTask(req),
  decomposeTask: (req: DecomposeTaskRequest) => api().decomposeTask(req),

  listTaskItems: (req: ListByWorkspaceRequest) => api().listTaskItems(req),
  createTaskItem: (req: CreateTaskItemRequest) => api().createTaskItem(req),
  updateTaskItem: (req: UpdateTaskItemRequest) => api().updateTaskItem(req),
  deleteTaskItem: (req: DeleteTaskItemRequest) => api().deleteTaskItem(req),
  executeTaskItem: (req: ExecuteTaskItemRequest) => api().executeTaskItem(req),

  catalog: (req: ListByWorkspaceRequest) => api().catalog(req),
  gitDiff: (req: ListByWorkspaceRequest) => api().gitDiff(req),
  gitStatus: (req: ListByWorkspaceRequest) => api().gitStatus(req),
  gitFileDiff: (req: GitFileDiffRequest) => api().gitFileDiff(req),
  gitStagePaths: (req: GitStagePathsRequest) => api().gitStagePaths(req),
  gitUnstagePaths: (req: GitUnstagePathsRequest) => api().gitUnstagePaths(req),
  gitCommit: (req: GitCommitRequest) => api().gitCommit(req),

  seedPreset: (req: SeedPresetRequest) => api().seedPreset(req),
  requestAiDecompose: (req: RequestAiDecomposeRequest) => api().requestAiDecompose(req),
  importDecomposition: (req: ImportDecompositionRequest) => api().importDecomposition(req),
  requestAiWorkflowGen: (req: RequestAiWorkflowGenRequest) => api().requestAiWorkflowGen(req),
  importWorkflowDraft: (req: ImportWorkflowDraftRequest) => api().importWorkflowDraft(req),
  requestAiWorkflowEdit: (req: RequestAiWorkflowEditRequest) =>
    api().requestAiWorkflowEdit(req),
  importWorkflowEdit: (req: ImportWorkflowEditRequest) => api().importWorkflowEdit(req),

  onChanged: (listener: (e: WorkOSChangedEvent) => void) => api().onChanged(listener),
};

export type {
  Step,
  Workflow,
  Task,
  TaskItem,
  ListByWorkspaceRequest,
  CreateStepRequest,
  UpdateStepRequest,
  DeleteStepRequest,
  FindDuplicateStepsRequest,
  FindDuplicateStepsResponse,
  MergeDuplicateStepsRequest,
  MergeDuplicateStepsResponse,
  DuplicateStepGroup,
  CreateWorkflowRequest,
  UpdateWorkflowRequest,
  DeleteWorkflowRequest,
  CreateTaskRequest,
  UpdateTaskRequest,
  DeleteTaskRequest,
  DecomposeTaskRequest,
  CreateTaskItemRequest,
  UpdateTaskItemRequest,
  DeleteTaskItemRequest,
  ExecuteTaskItemRequest,
  ExecuteTaskItemResponse,
  CatalogResponse,
  GitDiffResponse,
  GitCommitRequest,
  GitCommitResponse,
  GitFileDiffRequest,
  GitFileDiffResponse,
  GitStatusResponse,
  GitStagePathsRequest,
  GitUnstagePathsRequest,
  FileChange,
  FileChangeKind,
  ImportDecompositionRequest,
  ImportWorkflowDraftRequest,
  ImportWorkflowDraftResponse,
  ImportWorkflowEditRequest,
  ImportWorkflowEditResponse,
  RequestAiDecomposeRequest,
  RequestAiDecomposeResponse,
  RequestAiWorkflowEditRequest,
  RequestAiWorkflowEditResponse,
  RequestAiWorkflowGenRequest,
  RequestAiWorkflowGenResponse,
  SeedPresetRequest,
  SeedPresetResponse,
  WorkOSChangedEvent,
};
